name: picard ReorderSam
description: |
  Reorders SAM or BAM files according to a external reference list.
authors:
  - Alexander Hübner
input:
  - sam/bam file
output:
  - sam/bam file.
notes: |
  * The `java_opts` param allows for additional arguments to be passed to the java compiler, e.g. "-XX:ParallelGCThreads=10" (not for `-XmX` or `-Djava.io.tmpdir`, since they are handled automatically).
  * The `extra` param allows for additional program arguments.
  * `--TMP_DIR` is automatically set by `resources.tmpdir`
  * For more information see, https://broadinstitute.github.io/picard/command-line-overview.html#ReorderSam
